# Generated by Django 4.2.6 on 2023-10-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resume", "0001_initial"),
        ("user", "0001_initial"),
        ("vacancy", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserViewedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to="user.user",
                        verbose_name="Вакансия",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employers",
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просьотр",
                "verbose_name_plural": "Просмотры",
            },
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трекер",
                "verbose_name_plural": "Трекер",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Не известно"),
                            (1, "Принято"),
                            (2, "Отказ"),
                            (3, "Ожидание"),
                        ],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vacancy.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приглашенный",
                "verbose_name_plural": "Приглашенные",
                "default_related_name": "invitations",
            },
        ),
        migrations.CreateModel(
            name="Interested",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vacancy.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заинтерисованный",
                "verbose_name_plural": "Заинтересованные",
                "default_related_name": "interested",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vacancy.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный",
                "verbose_name_plural": "Избранные",
                "default_related_name": "favorites",
            },
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vacancy.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение подходящих вакансий",
                "verbose_name_plural": "Сравнения подходящих вакансий",
                "default_related_name": "comparisons",
            },
        ),
        migrations.AddConstraint(
            model_name="userviewedresume",
            constraint=models.UniqueConstraint(
                fields=("employer", "resume"), name="unique_employer_resume"
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "resume"), name="unique_invitation_resume"
            ),
        ),
        migrations.AddConstraint(
            model_name="interested",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "resume"), name="unique_interested_resume"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "resume"), name="unique_favorite_resume"
            ),
        ),
        migrations.AddConstraint(
            model_name="comparison",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "resume"), name="unique_comparison_resume"
            ),
        ),
    ]
