# Generated by Django 4.2.6 on 2023-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение подходящих вакансий",
                "verbose_name_plural": "Сравнения подходящих вакансий",
                "default_related_name": "comparisons",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный",
                "verbose_name_plural": "Избранные",
                "default_related_name": "favorites",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Не известно"),
                            (1, "Принято"),
                            (2, "Отказ"),
                            (3, "Ожидание"),
                        ],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приглашенный",
                "verbose_name_plural": "Приглашенные",
                "default_related_name": "invitations",
            },
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трекер",
                "verbose_name_plural": "Трекер",
            },
        ),
        migrations.CreateModel(
            name="UserViewedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просьотр",
                "verbose_name_plural": "Просмотры",
            },
        ),
    ]
