# Generated by Django 4.2.6 on 2023-10-28 17:33

import django.core.validators
from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Максимум 150 символов.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-zA-Z0-9]+$"
                            ),
                            user.validators.username_validator,
                        ],
                        verbose_name="Логин",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Максимум 150 символов.",
                        max_length=150,
                        verbose_name="Пароль",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Максимум 150 символов.",
                        max_length=255,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Максимум 150 символов.",
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[а-яА-ЯёЁa-zA-Z0-9]+$"
                            ),
                            user.validators.username_validator,
                        ],
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Максимум 150 символов.",
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[а-яА-ЯёЁa-zA-Z0-9]+$"
                            ),
                            user.validators.username_validator,
                        ],
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "last_visited",
                    models.CharField(verbose_name="Последний визит"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
