# Generated by Django 4.2.6 on 2023-10-22 19:34

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Максимум 150 символов.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$'), user.validators.username_validator], verbose_name='Логин')),
                ('password', models.CharField(help_text='Максимум 150 символов.', max_length=150, verbose_name='Пароль')),
                ('email', models.EmailField(help_text='Максимум 150 символов.', max_length=255, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(help_text='Максимум 150 символов.', max_length=150, validators=[django.core.validators.RegexValidator(regex='^[а-яА-ЯёЁa-zA-Z0-9]+$'), user.validators.username_validator], verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Максимум 150 символов.', max_length=150, validators=[django.core.validators.RegexValidator(regex='^[а-яА-ЯёЁa-zA-Z0-9]+$'), user.validators.username_validator], verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicker', models.ForeignKey(help_text='Наниматель', on_delete=django.db.models.deletion.CASCADE, related_name='likeds', to=settings.AUTH_USER_MODEL, verbose_name='Кто кликнул')),
                ('liked', models.ForeignKey(help_text='Наниматель', on_delete=django.db.models.deletion.CASCADE, related_name='clickers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('clicker', 'liked'), name='unique_clicker_liked'),
        ),
    ]
