# Generated by Django 4.2.6 on 2023-10-23 00:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Важность навыка",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Как минимум 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "Как максимум 5"
                            ),
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.CreateModel(
            name="NameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "namemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vacancy.namemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["name"],
            },
            bases=("vacancy.namemodel",),
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "namemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vacancy.namemodel",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание вакансии",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["name"],
            },
            bases=("vacancy.namemodel",),
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "namemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vacancy.namemodel",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="job_titles",
                        through="vacancy.JobSkill",
                        to="vacancy.skill",
                        verbose_name="Навыки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
            },
            bases=("vacancy.namemodel",),
        ),
        migrations.AddField(
            model_name="jobskill",
            name="job_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill",
                to="vacancy.jobtitle",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="jobskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_title",
                to="vacancy.skill",
                verbose_name="Навыки",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobskill",
            constraint=models.UniqueConstraint(
                fields=("job_title", "skill"), name="unique_job_skill"
            ),
        ),
    ]
